security:
    encoders:
        Tex\UsuarioBundle\Entity\User:
            algorithm:        sha512
            iterations:       1
            encode_as_base64: false

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: UsuarioBundle:User, property: email }

    firewalls:
        secured_area:
            pattern:    ^/  
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check                
                default_target_path: Base_site                
            logout:
                path: User_logout
                target: User_index            
            remember_me:
                key: tex123456
                lifetime: 3600
                path: /login
    access_control:
        - { path: ^/(login|create_user), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/index, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/edit_profile/, roles: ROLE_USER }
        - { path: ^/create_project/, roles: ROLE_USER }
        - { path: ^/admin/*, roles: [ROLE_ADMIN, ROLE_USER] }