Tex\TexnoBundle\Entity\Extras:
    type: entity
    table: extras
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomeExtra:
            type: string
            length: 255
            column: nome_extra
        valore:
            type: float
        idPerson:
            type: integer
            column: id_person
    lifecycleCallbacks: {  }
